apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xmas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # custom
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - xmas.algosup.com
    secretName: xmas-tls
  rules:
  - host: xmas.algosup.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: xmas
            port:
              number: 80