apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmas-deployment
spec:
  selector:
    matchLabels:
      app: xmas
  #replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xmas
    spec:
      containers:
      - name: xmas
        image: nginximages.azurecr.io/nginximage:latest
        imagePullPolicy: Always
        resources:
        # Requests and limits are mendatory for AKS
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1024m
            memory: 256Mi
        ports:
        - containerPort: 80
