apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmas-deployment
  labels:
    app: xmas
spec:
  selector:
    matchLabels:
      app: xmas
  template:
    metadata:
      labels:
        app: xmas
    spec:
      containers:
      - name: xmas
        image: xmas-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80