apiVersion: v1
kind: Service
metadata:
  name: xmas-service
  labels:
    app: xmas
    uri: xmas.algosup.com
spec:
  selector:
    app: xmas
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80