apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmas-deployment
  labels:
    app: xmas
spec:
  selector:
    matchLabels:
      app: xmas
  template:
    metadata:
      labels:
        app: xmas
    spec:
      containers:
      - name: xmas
        image: xmasimages.azurecr.io/xmas-image:latest
        resources:
        # Requests and limits are mendatory for AKS
          requests:
            cpu: 125m
            memory: 32Mi
          limits:
            cpu: "500m"
            memory: "128Mi"
        ports:
        - containerPort: 80