apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmas
spec:
  selector:
    matchLabels:
      app: xmas
  replicas: 1
  template:
    metadata:
      labels:
        app: xmas
    spec:
      containers:
        - image: k8sxmasimages.azurecr.io/k8sxmasimage:latest
          imagePullPolicy: Always
          name: xmas
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 4000m
              memory: 1024Mi
            
